Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.hostname = "srv-seguro"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  # Sync scripts/ directory into the VM at /vagrant/scripts
  config.vm.synced_folder "../scripts", "/vagrant/scripts"
end
